package com.zuxia.entity;

import java.util.ArrayList;
import java.util.List;

// Generated 2009-11-25 11:12:27 by Hibernate Tools 3.2.4.GA

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private Integer cityCd;
	/**
	 * province属性概述
	 * 
	 */
	private Province province;
	private String cityName;
	/**
	 * users属性概述
	 * 
	 */
	private List<User> users = new ArrayList<User>();
	/**
	 * cityCd属性的get方法
	 * @return the cityCd
	 */
	public Integer getCityCd() {
		return cityCd;
	}
	/**
	 * cityCd属性的set方法
	 * @param cityCd the cityCd to set
	 */
	public void setCityCd(Integer cityCd) {
		this.cityCd = cityCd;
	}
	/**
	 * province属性的get方法
	 * @return the province
	 */
	public Province getProvince() {
		return province;
	}
	/**
	 * province属性的set方法
	 * @param province the province to set
	 */
	public void setProvince(Province province) {
		this.province = province;
	}
	/**
	 * cityName属性的get方法
	 * @return the cityName
	 */
	public String getCityName() {
		return cityName;
	}
	/**
	 * cityName属性的set方法
	 * @param cityName the cityName to set
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}
	/**
	 * users属性的get方法
	 * @return the users
	 */
	public List<User> getUsers() {
		return users;
	}
	/**
	 * users属性的set方法
	 * @param users the users to set
	 */
	public void setUsers(List<User> users) {
		this.users = users;
	}

}
