package com.zuxia.entity;

// Generated 2009-11-25 11:12:27 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * FellowNote generated by hbm2java
 */
public class FellowNote implements java.io.Serializable {

	/**
	 * serialVersionUID属性概述
	 * 
	 */
	private static final long serialVersionUID = -4263761897461937747L;
	private Integer fellowNoteCd;
	/**
	 * note属性概述 主帖子CODE
	 */
	private Note note;
	/**
	 * user属性概述 跟贴用户CODE
	 */
	private User user;
	private String flwContent;
	private Date publishDate;

	/**
	 * fellowNoteCd属性的get方法
	 * 
	 * @return the fellowNoteCd
	 */
	public Integer getFellowNoteCd() {
		return fellowNoteCd;
	}

	/**
	 * fellowNoteCd属性的set方法
	 * 
	 * @param fellowNoteCd
	 *            the fellowNoteCd to set
	 */
	public void setFellowNoteCd(Integer fellowNoteCd) {
		this.fellowNoteCd = fellowNoteCd;
	}

	/**
	 * note属性的get方法
	 * 
	 * @return the note
	 */
	public Note getNote() {
		return note;
	}

	/**
	 * note属性的set方法
	 * 
	 * @param note
	 *            the note to set
	 */
	public void setNote(Note note) {
		this.note = note;
	}

	/**
	 * user属性的get方法
	 * 
	 * @return the user
	 */
	public User getUser() {
		return user;
	}

	/**
	 * user属性的set方法
	 * 
	 * @param user
	 *            the user to set
	 */
	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * flwContent属性的get方法
	 * 
	 * @return the flwContent
	 */
	public String getFlwContent() {
		return flwContent;
	}

	/**
	 * flwContent属性的set方法
	 * 
	 * @param flwContent
	 *            the flwContent to set
	 */
	public void setFlwContent(String flwContent) {
		this.flwContent = flwContent;
	}

	/**
	 * publishDate属性的get方法
	 * 
	 * @return the publishDate
	 */
	public Date getPublishDate() {
		return publishDate;
	}

	/**
	 * publishDate属性的set方法
	 * 
	 * @param publishDate
	 *            the publishDate to set
	 */
	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

}
