package com.zuxia.entity;

// Generated 2009-11-25 11:12:27 by Hibernate Tools 3.2.4.GA

/**
 * SafeQuestion generated by hbm2java
 */
public class SafeQuestion implements java.io.Serializable {

	private int userCd;
	/**
	 * questionMaster属性概述
	 * 
	 */
	private QuestionMaster questionMaster;
	private String answer;
	private User user;

	/**
	 * userCd属性的get方法
	 * 
	 * @return the userCd
	 */
	public int getUserCd() {
		return userCd;
	}

	/**
	 * userCd属性的set方法
	 * 
	 * @param userCd
	 *            the userCd to set
	 */
	public void setUserCd(int userCd) {
		this.userCd = userCd;
	}

	/**
	 * questionMaster属性的get方法
	 * 
	 * @return the questionMaster
	 */
	public QuestionMaster getQuestionMaster() {
		return questionMaster;
	}

	/**
	 * questionMaster属性的set方法
	 * 
	 * @param questionMaster
	 *            the questionMaster to set
	 */
	public void setQuestionMaster(QuestionMaster questionMaster) {
		this.questionMaster = questionMaster;
	}

	/**
	 * answer属性的get方法
	 * 
	 * @return the answer
	 */
	public String getAnswer() {
		return answer;
	}

	/**
	 * answer属性的set方法
	 * 
	 * @param answer
	 *            the answer to set
	 */
	public void setAnswer(String answer) {
		this.answer = answer;
	}

	/**
	 * user属性的get方法
	 * 
	 * @return the user
	 */
	public User getUser() {
		return user;
	}

	/**
	 * user属性的set方法
	 * 
	 * @param user
	 *            the user to set
	 */
	public void setUser(User user) {
		this.user = user;
	}

}
