package com.zuxia.entity;

// Generated 2009-11-25 11:12:27 by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userCd;
	private String userName;
	private int roleCd;
	private String sex;
	private String photoPath;
	private Date birthday;
	private Integer provinceCd;
	private Integer cityCd;
	private String email;
	private Integer score;
	private Date lastLoginDate;
	private Date registDate;
	private String comment;
	private Password password;
	/**
	 * modules属性概述 主版块
	 */
	private List<Module> modules = new ArrayList<Module>();
	/**
	 * childModules属性概述 子版块
	 */
	private List<ChildModule> childModules = new ArrayList<ChildModule>();

	/**
	 * childModules属性的get方法
	 * @return the childModules
	 */
	public List<ChildModule> getChildModules() {
		return childModules;
	}

	/**
	 * childModules属性的set方法
	 * @param childModules the childModules to set
	 */
	public void setChildModules(List<ChildModule> childModules) {
		this.childModules = childModules;
	}

	/**
	 * modules属性的get方法
	 * 
	 * @return the modules
	 */
	public List<Module> getModules() {
		return modules;
	}

	/**
	 * modules属性的set方法
	 * 
	 * @param modules
	 *            the modules to set
	 */
	public void setModules(List<Module> modules) {
		this.modules = modules;
	}

	public Password getPassword() {
		return password;
	}

	public void setPassword(Password password) {
		this.password = password;
	}

	public User() {
	}

	public User(String userName, int roleCd, String sex) {
		this.userName = userName;
		this.roleCd = roleCd;
		this.sex = sex;
	}

	public User(String userName, int roleCd, String sex, String photoPath,
			Date birthday, Integer provinceCd, Integer cityCd, String email,
			Integer score, Date lastLoginDate, Date registDate, String comment) {
		this.userName = userName;
		this.roleCd = roleCd;
		this.sex = sex;
		this.photoPath = photoPath;
		this.birthday = birthday;
		this.provinceCd = provinceCd;
		this.cityCd = cityCd;
		this.email = email;
		this.score = score;
		this.lastLoginDate = lastLoginDate;
		this.registDate = registDate;
		this.comment = comment;
	}

	public Integer getUserCd() {
		return this.userCd;
	}

	public void setUserCd(Integer userCd) {
		this.userCd = userCd;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public int getRoleCd() {
		return this.roleCd;
	}

	public void setRoleCd(int roleCd) {
		this.roleCd = roleCd;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPhotoPath() {
		return this.photoPath;
	}

	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Integer getProvinceCd() {
		return this.provinceCd;
	}

	public void setProvinceCd(Integer provinceCd) {
		this.provinceCd = provinceCd;
	}

	public Integer getCityCd() {
		return this.cityCd;
	}

	public void setCityCd(Integer cityCd) {
		this.cityCd = cityCd;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public Date getRegistDate() {
		return this.registDate;
	}

	public void setRegistDate(Date registDate) {
		this.registDate = registDate;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
