package com.zuxia.entity;

// Generated 2009-11-25 11:12:27 by Hibernate Tools 3.2.4.GA

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private Integer cityCd;
	private Integer provinceCd;
	private String cityName;

	public City() {
	}

	public City(Integer provinceCd, String cityName) {
		this.provinceCd = provinceCd;
		this.cityName = cityName;
	}

	public Integer getCityCd() {
		return this.cityCd;
	}

	public void setCityCd(Integer cityCd) {
		this.cityCd = cityCd;
	}

	public Integer getProvinceCd() {
		return this.provinceCd;
	}

	public void setProvinceCd(Integer provinceCd) {
		this.provinceCd = provinceCd;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

}
