package com.zuxia.entity;

// Generated 2009-11-25 11:12:27 by Hibernate Tools 3.2.4.GA

/**
 * Module generated by hbm2java
 */
public class Module implements java.io.Serializable {

	private Integer moduleCd;
	private String moduleName;
	private Integer moduleMasterCd;

	public Module() {
	}

	public Module(String moduleName, Integer moduleMasterCd) {
		this.moduleName = moduleName;
		this.moduleMasterCd = moduleMasterCd;
	}

	public Integer getModuleCd() {
		return this.moduleCd;
	}

	public void setModuleCd(Integer moduleCd) {
		this.moduleCd = moduleCd;
	}

	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	public Integer getModuleMasterCd() {
		return this.moduleMasterCd;
	}

	public void setModuleMasterCd(Integer moduleMasterCd) {
		this.moduleMasterCd = moduleMasterCd;
	}

}
