package com.zuxia.entity;

// Generated 2009-11-25 11:12:27 by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Note generated by hbm2java
 */
public class Note implements java.io.Serializable {

	/**
	 * serialVersionUID属性概述
	 * 
	 */
	private static final long serialVersionUID = 7478822662932661205L;
	private Integer noteCd;
	/**
	 * user属性概述 用户
	 */
	private User user;
	/**
	 * module属性概述 主版块
	 */
	private Module module;
	/**
	 * childModule属性概述 子版块
	 */
	private ChildModule childModule;
	private String title;
	private String content;
	private Date publishDate;
	private int point;
	/**
	 * fellowNote属性概述 跟帖
	 */
	private List<FellowNote> fellowNote = new ArrayList<FellowNote>();

	/**
	 * noteCd属性的get方法
	 * 
	 * @return the noteCd
	 */
	public Integer getNoteCd() {
		return noteCd;
	}

	/**
	 * noteCd属性的set方法
	 * 
	 * @param noteCd
	 *            the noteCd to set
	 */
	public void setNoteCd(Integer noteCd) {
		this.noteCd = noteCd;
	}

	/**
	 * user属性的get方法
	 * 
	 * @return the user
	 */
	public User getUser() {
		return user;
	}

	/**
	 * user属性的set方法
	 * 
	 * @param user
	 *            the user to set
	 */
	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * module属性的get方法
	 * 
	 * @return the module
	 */
	public Module getModule() {
		return module;
	}

	/**
	 * module属性的set方法
	 * 
	 * @param module
	 *            the module to set
	 */
	public void setModule(Module module) {
		this.module = module;
	}

	/**
	 * childModule属性的get方法
	 * 
	 * @return the childModule
	 */
	public ChildModule getChildModule() {
		return childModule;
	}

	/**
	 * childModule属性的set方法
	 * 
	 * @param childModule
	 *            the childModule to set
	 */
	public void setChildModule(ChildModule childModule) {
		this.childModule = childModule;
	}

	/**
	 * title属性的get方法
	 * 
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * title属性的set方法
	 * 
	 * @param title
	 *            the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * content属性的get方法
	 * 
	 * @return the content
	 */
	public String getContent() {
		return content;
	}

	/**
	 * content属性的set方法
	 * 
	 * @param content
	 *            the content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * publishDate属性的get方法
	 * 
	 * @return the publishDate
	 */
	public Date getPublishDate() {
		return publishDate;
	}

	/**
	 * publishDate属性的set方法
	 * 
	 * @param publishDate
	 *            the publishDate to set
	 */
	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	/**
	 * fellowNote属性的get方法
	 * 
	 * @return the fellowNote
	 */
	public List<FellowNote> getFellowNote() {
		return fellowNote;
	}

	/**
	 * fellowNote属性的set方法
	 * 
	 * @param fellowNote
	 *            the fellowNote to set
	 */
	public void setFellowNote(List<FellowNote> fellowNote) {
		this.fellowNote = fellowNote;
	}

	/**
	 * point属性的get方法
	 * 
	 * @return the point
	 */
	public int getPoint() {
		return point;
	}

	/**
	 * point属性的set方法
	 * 
	 * @param point
	 *            the point to set
	 */
	public void setPoint(int point) {
		this.point = point;
	}

}
