package com.zuxia.entity;

// Generated 2009-11-25 11:12:27 by Hibernate Tools 3.2.4.GA

/**
 * Password generated by hbm2java
 */
public class Password implements java.io.Serializable {

	/**
	 * serialVersionUID Ù–‘∏≈ ˆ
	 * 
	 */
	private static final long serialVersionUID = -8983656626549307137L;
	private int userCd;
	private String password;
	private User user;
	

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Password() {
	}

	public Password(int userCd) {
		this.userCd = userCd;
	}

	public Password(int userCd, String password) {
		this.userCd = userCd;
		this.password = password;
	}

	public int getUserCd() {
		return this.userCd;
	}

	public void setUserCd(int userCd) {
		this.userCd = userCd;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
