package com.zuxia.entity;

// Generated 2009-11-23 12:07:21 by Hibernate Tools 3.2.4.GA

/**
 * QuestionMaster generated by hbm2java
 */
public class QuestionMaster implements java.io.Serializable {

	private Integer questionCd;
	private String question;

	public QuestionMaster() {
	}

	public QuestionMaster(String question) {
		this.question = question;
	}

	public Integer getQuestionCd() {
		return this.questionCd;
	}

	public void setQuestionCd(Integer questionCd) {
		this.questionCd = questionCd;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

}
