package com.zuxia.entity;

// Generated 2009-11-25 11:12:27 by Hibernate Tools 3.2.4.GA

/**
 * SafeQuestion generated by hbm2java
 */
public class SafeQuestion implements java.io.Serializable {

	private int userCd;
	private Integer questionCd;
	private String answer;

	public SafeQuestion() {
	}

	public SafeQuestion(int userCd) {
		this.userCd = userCd;
	}

	public SafeQuestion(int userCd, Integer questionCd, String answer) {
		this.userCd = userCd;
		this.questionCd = questionCd;
		this.answer = answer;
	}

	public int getUserCd() {
		return this.userCd;
	}

	public void setUserCd(int userCd) {
		this.userCd = userCd;
	}

	public Integer getQuestionCd() {
		return this.questionCd;
	}

	public void setQuestionCd(Integer questionCd) {
		this.questionCd = questionCd;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
